application: appengine-backbone

version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /app/assets
  static_dir: app/assets
- url: .*
  script: main.app
